In [42]:
import pandas as pd, pathlib as pl
df = pd.read_parquet(r"C:\Users\tgati\molder-rl\data\interim\molding_labeled.parquet")
df["Reason"] = df["Reason"].fillna("No failure")

# Basic integrity
print("Rows :", len(df))
print("Labels:", df["label"].value_counts(normalize=True))
assert df.isna().sum().sum() == 0, "Missing values!"

# Quick numeric summary
summary = df.describe().T
summary.head()

Rows : 7996
Labels: label
0    0.991121
1    0.008879
Name: proportion, dtype: float64

,count,mean,std,min,25%,50%,75%,max
PART_FACT_SERIAL,7996.0,11.248749,5.005191,2.00,9.00,10.000000,13.000000,24.000000
Injection_Time,7996.0,8.242189,3.107724,1.05,9.52,9.560000,9.590000,16.309999
Filling_Time,7996.0,3.896309,1.284451,0.93,4.40,4.440000,4.470000,8.270000
Plasticizing_Time,7996.0,16.209505,1.443720,10.92,16.58,16.799999,16.889999,21.120001
Cycle_Time,7996.0,59.900902,0.885680,58.84,59.52,59.520000,59.560001,66.860001